name: Deploy Website

on:
  push:
    branches:
      - Task-2

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./Task-3/arjunb-5@mulearn

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
